name: Run PR checks
run-name: "Type and linter checks for PR #${{ github.event.pull_request.number }}"

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION_STRING }}
      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix 'packages/web'
      - name: Lint SST app
        run: npm run lint
      - name: Lint Next.js site
        working-directory: ./packages/web
        run: npm run lint
  typecheck:
    name: Run typechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION_STRING }}
      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix 'packages/web'
      - name: Typecheck SST app
        run: npm run typecheck
      - name: Typecheck Next.js site
        working-directory: ./packages/web
        run: npm run typecheck
