name: Develop PR build
run-name: "Build test for develop PR #${{ github.event.pull_request.number }}"

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Verify build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION_STRING }}
      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix 'packages/web'
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DEV_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true
      - name: Build SST app
        run: npx sst build --stage dev
